import { IconType } from "react-icons";
import {
  FaCode,
  FaBriefcase,
  FaBullhorn,
  FaServer,
  FaPalette,
  FaBrain,
  FaUserGraduate,
  FaHeartbeat,
  FaMusic,
  FaChalkboardTeacher,
  FaPaintBrush,
  FaCamera,
  FaLaptop,
  FaPenNib, // For Writing
  FaCogs,   // For Engineering
  FaMoneyBillWave, // For Finance
} from "react-icons/fa";

export interface CategoryWithIcon {
  value: string;
  label: string;
  icon: IconType;
  children?: { value: string; label: string }[];
}

export const COURSE_CATEGORIES_WITH_ICONS: CategoryWithIcon[] = [
  {
    value: "development",
    label: "Development",
    icon: FaCode,
    children: [
      { value: "web_development", label: "Web Development" },
      { value: "mobile_apps", label: "Mobile Apps" },
      { value: "programming", label: "Programming" },
      { value: "game_development", label: "Game Development" },
      { value: "databases", label: "Databases" },
      { value: "software_testing", label: "Software Testing" },
      { value: "software_engineering", label: "Software Engineering" },
      { value: "development_tools", label: "Development Tools" },
      { value: "ecommerce", label: "Ecommerce" },
      { value: "python", label: "Python" },
      { value: "ai_agents_agentic_ai", label: "AI Agents & Agentic AI" },
      { value: "artificial_intelligence", label: "Artificial Intelligence (AI)" },
      { value: "unreal_engine", label: "Unreal Engine" },
      { value: "data_science", label: "Data Science" },
      { value: "react_js", label: "React JS" },
      { value: "java", label: "Java" },
      { value: "unity", label: "Unity" },
      { value: "large_language_models", label: "Large Language Models (LLM)" },
      { value: "csharp", label: "C# (programming language)" },
      { value: "javascript", label: "JavaScript" },
      { value: "generative_ai", label: "Generative AI (GenAI)" },
      { value: "machine_learning", label: "Machine Learning" },
      { value: "cpp", label: "C++ (programming language)" },
      { value: "game_development_fundamentals", label: "Game Development Fundamentals" },
      { value: "google_flutter", label: "Google Flutter" },
      { value: "sql", label: "SQL" },
      { value: "angular", label: "Angular" },
      { value: "docker", label: "Docker" },
    ],
  },
  {
    value: "business",
    label: "Business",
    icon: FaBriefcase,
    children: [
      { value: "entrepreneurship", label: "Entrepreneurship" },
      { value: "communication", label: "Communication" },
      { value: "management", label: "Management" },
      { value: "sales", label: "Sales" },
      { value: "strategy", label: "Strategy" },
      { value: "operations", label: "Operations" },
      { value: "project_management", label: "Project Management" },
      { value: "business_law", label: "Business Law" },
      { value: "data_analytics", label: "Data Analytics" },
      { value: "home_business", label: "Home Business" },
      { value: "human_resources", label: "Human Resources" },
      { value: "industry", label: "Industry" },
      { value: "media", label: "Media" },
      { value: "real_estate", label: "Real Estate" },
      { value: "other", label: "Other" },
      { value: "pmp", label: "PMI Project Management Professional (PMP)" },
      { value: "microsoft_power_bi", label: "Microsoft Power BI" },
      { value: "project_management", label: "Project Management" },
      { value: "sql", label: "SQL" },
      { value: "capm", label: "PMI Certified Associate in Project Management (CAPM)" },
      { value: "pmbok", label: "PMI PMBOK" },
      { value: "data_analysis", label: "Data Analysis" },
      { value: "data_modeling", label: "Data Modeling" },
      { value: "artificial_intelligence", label: "Artificial Intelligence (AI)" },
      { value: "real_estate_investing", label: "Real Estate Investing" },
      { value: "business_analysis", label: "Business Analysis" },
      { value: "generative_ai", label: "Generative AI (GenAI)" },
      { value: "communication_skills", label: "Communication Skills" },
      { value: "business_strategy", label: "Business Strategy" },
      { value: "chatgpt", label: "ChatGPT" },
      { value: "product_management", label: "Product Management" },
      { value: "sales_skills", label: "Sales Skills" },
      { value: "human_resources", label: "Human Resources" },
      { value: "leadership", label: "Leadership" },
      { value: "business_fundamentals", label: "Business Fundamentals" },
      { value: "finance", label: "Finance" }, // keep for backward compatibility if needed
      { value: "python", label: "Python" },
      { value: "microsoft_excel", label: "Microsoft Excel" },
    ],
  },
  {
    value: "finance",
    label: "Finance",
    icon: FaMoneyBillWave,
    children: [
      { value: "finance_accounting", label: "Finance & Accounting" },
      { value: "stock_trading", label: "Stock Trading" },
      { value: "investing", label: "Investing" },
      { value: "financial_analysis", label: "Financial Analysis" },
      { value: "accounting", label: "Accounting" },
      { value: "forex_trading", label: "Forex Trading" },
      { value: "day_trading", label: "Day Trading" },
      { value: "technical_analysis", label: "Technical Analysis (finance)" },
      { value: "quickbooks", label: "QuickBooks" },
      { value: "algorithmic_trading", label: "Algorithmic Trading" },
      { value: "financial_modeling", label: "Financial Modeling" },
      { value: "options_trading", label: "Options Trading" },
      { value: "cryptocurrency", label: "Cryptocurrency" },
      { value: "financial_markets", label: "Financial Markets" },
      { value: "bookkeeping", label: "Bookkeeping" },
      { value: "finance_fundamentals", label: "Finance Fundamentals" },
      { value: "personal_finance", label: "Personal Finance" },
      { value: "financial_trading", label: "Financial Trading" },
      { value: "aml", label: "Anti-Money Laundering (AML)" },
      { value: "microsoft_excel", label: "Microsoft Excel" },
      { value: "python", label: "Python" },
    ],
  },
  {
    value: "it_software",
    label: "IT & Software",
    icon: FaServer,
    children: [
      { value: "it_certification", label: "IT Certification" },
      { value: "network_security", label: "Network & Security" },
      { value: "hardware", label: "Hardware" },
      { value: "operating_systems", label: "Operating Systems" },
      { value: "other", label: "Other" },
      { value: "aws_solutions_architect_associate", label: "AWS Certified Solutions Architect - Associate" },
      { value: "aws_cloud_practitioner", label: "AWS Certified Cloud Practitioner" },
      { value: "comptia_security_plus", label: "CompTIA Security+" },
      { value: "comptia_a_plus", label: "CompTIA A+" },
      { value: "amazon_aws", label: "Amazon AWS" },
      { value: "ccna", label: "Cisco Certified Network Associate (CCNA)" },
      { value: "ethical_hacking", label: "Ethical Hacking" },
      { value: "comptia_network_plus", label: "CompTIA Network+" },
      { value: "information_security", label: "Information Security" },
      { value: "cybersecurity", label: "Cybersecurity" },
      { value: "kubernetes", label: "Kubernetes" },
      { value: "aws_ai_practitioner", label: "AWS Certified AI Practitioner" },
      { value: "linux", label: "Linux" },
      { value: "az900", label: "AZ-900: Microsoft Azure Fundamentals" },
      { value: "artificial_intelligence", label: "Artificial Intelligence (AI)" },
      { value: "devops", label: "DevOps" },
      { value: "aws_genai_developer", label: "AWS Certified Generative AI Developer - Professional" },
      { value: "az104", label: "AZ-104: Microsoft Azure Administrator Associate" },
      { value: "aws_developer_associate", label: "AWS Certified Developer - Associate" },
      { value: "aigp", label: "Artificial Intelligence Governance Professional (AIGP)" },
    ],
  },
  {
    value: "office_productivity",
    label: "Office Productivity",
    icon: FaLaptop,
    children: [
      { value: "microsoft", label: "Microsoft" },
      { value: "apple", label: "Apple" },
      { value: "google", label: "Google" },
      { value: "sap", label: "SAP" },
      { value: "intuit", label: "Intuit" },
      { value: "salesforce", label: "Salesforce" },
      { value: "oracle", label: "Oracle" },
      { value: "other", label: "Other" },
      { value: "microsoft_excel", label: "Microsoft Excel" },
      { value: "chatgpt", label: "ChatGPT" },
      { value: "microsoft_power_bi", label: "Microsoft Power BI" },
      { value: "sap", label: "SAP" },
      { value: "microsoft_365", label: "Microsoft 365 (Office)" },
      { value: "microsoft_copilot", label: "Microsoft Copilot" },
      { value: "powerpoint", label: "PowerPoint" },
      { value: "excel_vba", label: "Excel VBA" },
      { value: "excel_formulas_functions", label: "Excel Formulas and Functions" },
      { value: "microsoft_sharepoint", label: "Microsoft SharePoint" },
      { value: "pivot_tables", label: "Pivot Tables" },
      { value: "artificial_intelligence", label: "Artificial Intelligence (AI)" },
      { value: "microsoft_power_automate", label: "Microsoft Power Automate" },
      { value: "google_sheets", label: "Google Sheets" },
      { value: "data_analysis", label: "Data Analysis" },
      { value: "google_gemini", label: "Google Gemini (Bard)" },
      { value: "sap_s4hana", label: "SAP S/4HANA" },
      { value: "microsoft_project", label: "Microsoft Project" },
      { value: "microsoft_word", label: "Microsoft Word" },
      { value: "power_pivot", label: "Power Pivot" },
    ],
  },
  {
    value: "personal_development",
    label: "Personal Development",
    icon: FaUserGraduate,
    children: [
      { value: "personal_transformation", label: "Personal Transformation" },
      { value: "leadership", label: "Leadership" },
      { value: "productivity", label: "Productivity" },
      { value: "personal_finance", label: "Personal Finance" },
      { value: "career_development", label: "Career Development" },
      { value: "parenting_relationships", label: "Parenting & Relationships" },
      { value: "happiness", label: "Happiness" },
      { value: "religion_spirituality", label: "Religion & Spirituality" },
      { value: "personal_brand_building", label: "Personal Brand Building" },
      { value: "creativity", label: "Creativity" },
      { value: "influence", label: "Influence" },
      { value: "self_esteem", label: "Self Esteem" },
      { value: "stress_management", label: "Stress Management" },
      { value: "memory_study_skills", label: "Memory & Study Skills" },
      { value: "motivation", label: "Motivation" },
      { value: "other", label: "Other" },
      { value: "generative_ai", label: "Generative AI (GenAI)" },
      { value: "life_coach_training", label: "Life Coach Training" },
      { value: "chatgpt", label: "ChatGPT" },
      { value: "communication_skills", label: "Communication Skills" },
      { value: "nlp", label: "Neuro-Linguistic Programming (NLP)" },
      { value: "personal_productivity", label: "Personal Productivity" },
      { value: "speed_reading", label: "Speed Reading" },
      { value: "memory", label: "Memory" },
      { value: "creative_writing", label: "Creative Writing" },
      { value: "coaching", label: "Coaching" },
      { value: "public_speaking", label: "Public Speaking" },
      { value: "time_management", label: "Time Management" },
      { value: "confidence", label: "Confidence" },
      { value: "artificial_intelligence", label: "Artificial Intelligence (AI)" },
      { value: "obsidian_app", label: "Obsidian App" },
      { value: "project_management", label: "Project Management" },
      { value: "spirituality", label: "Spirituality" },
    ],
  },
  {
    value: "design",
    label: "Design",
    icon: FaPalette,
    children: [
      { value: "web_design", label: "Web Design" },
      { value: "graphic_design", label: "Graphic Design" },
      { value: "design_tools", label: "Design Tools" },
      { value: "user_experience", label: "User Experience" },
      { value: "game_design", label: "Game Design" },
      { value: "design_thinking", label: "Design Thinking" },
      { value: "3d_animation", label: "3D & Animation" },
      { value: "fashion", label: "Fashion" },
      { value: "architectural_design", label: "Architectural Design" },
      { value: "interior_design", label: "Interior Design" },
      { value: "other", label: "Other" },
      { value: "blender", label: "Blender" },
      { value: "graphic_design", label: "Graphic Design" },
      { value: "3d_modeling", label: "3D Modeling" },
      { value: "drawing", label: "Drawing" },
      { value: "figma", label: "Figma" },
      { value: "ux_design", label: "User Experience (UX) Design" },
      { value: "autocad", label: "AutoCAD" },
      { value: "revit", label: "Revit" },
      { value: "canva", label: "Canva" },
      { value: "autodesk_fusion", label: "Autodesk Fusion" },
      { value: "adobe_photoshop", label: "Adobe Photoshop" },
      { value: "adobe_illustrator", label: "Adobe Illustrator" },
      { value: "3d_printing", label: "3D Printing" },
      { value: "adobe_after_effects", label: "Adobe After Effects" },
      { value: "solidworks", label: "SOLIDWORKS" },
      { value: "procreate", label: "Procreate Digital Illustration App" },
      { value: "web_design", label: "Web Design" },
      { value: "pixel_art", label: "Pixel Art" },
      { value: "motion_graphics", label: "Motion Graphics" },
      { value: "interior_design", label: "Interior Design" },
    ],
  },
  {
    value: "marketing",
    label: "Marketing",
    icon: FaBullhorn,
    children: [
      { value: "digital_marketing", label: "Digital Marketing" },
      { value: "seo", label: "Search Engine Optimization" },
      { value: "social_media_marketing", label: "Social Media Marketing" },
      { value: "branding", label: "Branding" },
      { value: "marketing_fundamentals", label: "Marketing Fundamentals" },
      { value: "analytics_automation", label: "Analytics & Automation" },
      { value: "public_relations", label: "Public Relations" },
      { value: "advertising", label: "Advertising" },
      { value: "video_mobile_marketing", label: "Video & Mobile Marketing" },
      { value: "content_marketing", label: "Content Marketing" },
      { value: "non_digital_marketing", label: "Non Digital Marketing" },
      { value: "growth_hacking", label: "Growth Hacking" },
      { value: "product_marketing", label: "Product Marketing" },
      { value: "affiliate_marketing", label: "Affiliate Marketing" },
      { value: "other", label: "Other" },
      { value: "digital_marketing", label: "Digital Marketing" },
      { value: "social_media_marketing", label: "Social Media Marketing" },
      { value: "seo", label: "Search Engine Optimization (SEO)" },
      { value: "marketing_strategy", label: "Marketing Strategy" },
      { value: "google_ads", label: "Google Ads (Adwords)" },
      { value: "social_media_management", label: "Social Media Management" },
      { value: "facebook_ads", label: "Facebook Ads" },
      { value: "youtube_marketing", label: "YouTube Marketing" },
      { value: "instagram_marketing", label: "Instagram Marketing" },
      { value: "internet_marketing", label: "Internet Marketing" },
      { value: "wordpress", label: "WordPress" },
      { value: "facebook_marketing", label: "Facebook Marketing" },
      { value: "copywriting", label: "Copywriting" },
      { value: "canva", label: "Canva" },
      { value: "youtube_audience_growth", label: "YouTube Audience Growth" },
      { value: "ai_content_generation", label: "AI Content Generation" },
      { value: "affiliate_marketing", label: "Affiliate Marketing" },
      { value: "google_analytics", label: "Google Analytics" },
      { value: "chatgpt", label: "ChatGPT" },
      { value: "google_ads_certification", label: "Google Ads Certification" },
    ],
  },
  {
    value: "lifestyle",
    label: "Lifestyle",
    icon: FaPaintBrush,
    children: [
      { value: "arts_crafts", label: "Arts & Crafts" },
      { value: "food_beverage", label: "Foods & Beverages" },
      { value: "beauty_makeup", label: "Beauty & Makeup" },
      { value: "travel", label: "Travel" },
      { value: "gaming", label: "Gaming" },
      { value: "home_improvement", label: "Home Improvement" },
      { value: "pet_care", label: "Pet Care & Training" },
      { value: "other", label: "Other" },
      { value: "drawing", label: "Drawing" },
      { value: "watercolor_painting", label: "Watercolor Painting" },
      { value: "energy_healing", label: "Energy Healing" },
      { value: "chess", label: "Chess" },
      { value: "sketching", label: "Sketching" },
      { value: "acrylic_painting", label: "Acrylic Painting" },
      { value: "astrology", label: "Astrology" },
      { value: "hypnotherapy", label: "Hypnotherapy" },
      { value: "figure_drawing", label: "Figure Drawing" },
      { value: "spiritual_healing", label: "Spiritual Healing" },
      { value: "cooking", label: "Cooking" },
      { value: "painting", label: "Painting" },
    ],
  },
  {
    value: "photography_video",
    label: "Photography",
    icon: FaCamera,
    children: [
      { value: "digital_photography", label: "Digital Photography" },
      { value: "photography_fundamentals", label: "Photography Fundamentals" },
      { value: "portraits", label: "Portraits" },
      { value: "landscape", label: "Landscape" },
      { value: "black_white", label: "Black & White" },
      { value: "photography_tools", label: "Photography Tools" },
      { value: "mobile_photography", label: "Mobile Photography" },
      { value: "travel_photography", label: "Travel Photography" },
      { value: "commercial_photography", label: "Commercial Photography" },
      { value: "wedding_photography", label: "Wedding Photography" },
      { value: "wildlife_photography", label: "Wildlife Photography" },
      { value: "video_design", label: "Video Design" },
      { value: "other", label: "Other" },
      { value: "video_editing", label: "Video Editing" },
      { value: "ai_content_generation", label: "AI Content Generation" },
      { value: "davinci_resolve", label: "DaVinci Resolve" },
      { value: "adobe_premiere_pro", label: "Adobe Premiere Pro" },
      { value: "capcut", label: "CapCut" },
      { value: "video_production", label: "Video Production" },
      { value: "adobe_lightroom", label: "Adobe Lightroom" },
      { value: "iphone_photography", label: "iPhone Photography" },
      { value: "adobe_after_effects", label: "Adobe After Effects" },
      { value: "color_grading", label: "Color Grading" },
      { value: "digital_camera_functionality", label: "Digital Camera Functionality" },
      { value: "videography", label: "Videography" },
      { value: "image_editing", label: "Image Editing" },
      { value: "generative_ai", label: "Generative AI (GenAI)" },
      { value: "portrait_photography", label: "Portrait Photography" },
      { value: "filmmaking", label: "Filmmaking" },
      { value: "adobe_photoshop", label: "Adobe Photoshop" },
      { value: "digital_photography", label: "Digital Photography" },
      { value: "final_cut_pro", label: "Final Cut Pro" },
    ],
  },
  {
    value: "health_fitness",
    label: "Health & Fitness",
    icon: FaHeartbeat,
    children: [
      { value: "fitness", label: "Fitness" },
      { value: "general_health", label: "General Health" },
      { value: "sports", label: "Sports" },
      { value: "nutrition", label: "Nutrition" },
      { value: "yoga", label: "Yoga" },
      { value: "mental_health", label: "Mental Health" },
      { value: "dieting", label: "Dieting" },
      { value: "self_defense", label: "Self Defense" },
      { value: "safety_first_aid", label: "Safety & First Aid" },
      { value: "dance", label: "Dance" },
      { value: "meditation", label: "Meditation" },
      { value: "other", label: "Other" },
      { value: "massage", label: "Massage" },
      { value: "pilates", label: "Pilates" },
      { value: "qigong", label: "Qigong" },
      { value: "breathing_techniques", label: "Breathing Techniques" },
      { value: "health", label: "Health" },
      { value: "cbt", label: "Cognitive Behavioral Therapy (CBT)" },
    ],
  },
  {
    value: "teacher_training",
    label: "Teacher & Training",
    icon: FaChalkboardTeacher,
    children: [
      { value: "instructional_design", label: "Instructional Design" },
      { value: "educational_development", label: "Educational Development" },
      { value: "teaching_tools", label: "Teaching Tools" },
      { value: "other", label: "Other" },
    ],
  },
  {
    value: "music",
    label: "Music",
    icon: FaMusic,
    children: [
      { value: "instruments", label: "Instruments" },
      { value: "production", label: "Production" },
      { value: "music_fundamentals", label: "Music Fundamentals" },
      { value: "vocals", label: "Vocals" },
      { value: "music_techniques", label: "Music Techniques" },
      { value: "music_software", label: "Music Software" },
      { value: "other", label: "Other" },
      { value: "guitar", label: "Guitar" },
      { value: "piano", label: "Piano" },
      { value: "music_theory", label: "Music Theory" },
      { value: "music_production", label: "Music Production" },
      { value: "singing", label: "Singing" },
      { value: "ableton_live", label: "Ableton Live" },
      { value: "keyboard_instrument", label: "Keyboard Instrument" },
      { value: "fl_studio", label: "FL Studio" },
      { value: "music_composition", label: "Music Composition" },
      { value: "logic_pro", label: "Logic Pro" },
      { value: "music_mixing", label: "Music Mixing" },
      { value: "songwriting", label: "Songwriting" },
      { value: "sound_design", label: "Sound Design" },
      { value: "bass_guitar", label: "Bass Guitar" },
      { value: "fingerstyle_guitar", label: "Fingerstyle Guitar" },
      { value: "piano_chords", label: "Piano Chords" },
      { value: "drums", label: "Drums" },
      { value: "electronic_music", label: "Electronic Music" },
      { value: "audio_engineering", label: "Audio Engineering" },
    ],
  },
  {
    value: "academics",
    label: "Academics",
    icon: FaBrain,
    children: [
      { value: "social_science", label: "Social Science" },
      { value: "math_science", label: "Math & Science" },
      { value: "humanities", label: "Humanities" },
      { value: "english_language", label: "English Language" },
      { value: "german_language", label: "German Language" },
      { value: "spanish_language", label: "Spanish Language" },
      { value: "french_language", label: "French Language" },
      { value: "math", label: "Math" },
      { value: "english_grammar", label: "English Grammar" },
      { value: "japanese_language", label: "Japanese Language" },
      { value: "ielts", label: "IELTS" },
      { value: "calculus", label: "Calculus" },
      { value: "statistics", label: "Statistics" },
      { value: "electrical_engineering", label: "Electrical Engineering" },
      { value: "english_conversation", label: "English Conversation" },
      { value: "mandarin_chinese_language", label: "Mandarin Chinese Language" },
      { value: "electrical_circuits", label: "Electrical Circuits" },
      { value: "italian_language", label: "Italian Language" },
      { value: "english_vocabulary", label: "English Vocabulary" },
      { value: "electricity", label: "Electricity" },
      { value: "mechanical_engineering", label: "Mechanical Engineering" },
      { value: "electronics", label: "Electronics" },
      { value: "automotive_engineering", label: "Automotive Engineering" },
    ],
  },
  {
    value: "engineering",
    label: "Engineering",
    icon: FaCogs,
    children: [
      { value: "electrical_engineering", label: "Electrical Engineering" },
      { value: "mechanical_engineering", label: "Mechanical Engineering" },
      { value: "electronics", label: "Electronics" },
      { value: "automotive_engineering", label: "Automotive Engineering" },
      { value: "electrical_circuits", label: "Electrical Circuits" },
      { value: "electricity", label: "Electricity" },
    ],
  },
  {
    value: "writing",
    label: "Writing",
    icon: FaPenNib,
    children: [
      { value: "creative_writing", label: "Creative Writing" },
      { value: "copywriting", label: "Copywriting" },
    ],
  },
  {
    value: "language",
    label: "Language",
    icon: FaUserGraduate,
    children: [
      { value: "english", label: "English" },
      { value: "spanish", label: "Spanish" },
      { value: "french", label: "French" },
      { value: "german", label: "German" },
      { value: "japanese", label: "Japanese" },
      { value: "portuguese", label: "Portuguese" },
      { value: "chinese", label: "Chinese" },
      { value: "russian", label: "Russian" },
      { value: "latin", label: "Latin" },
      { value: "arabic", label: "Arabic" },
      { value: "hebrew", label: "Hebrew" },
      { value: "italian", label: "Italian" },
      { value: "other", label: "Other" },
    ],
  },
];

export const COURSE_CATEGORIES = [
  {
    value: "development",
    label: "Development",
    children: [
      { value: "web_development", label: "Web Development" },
      { value: "mobile_apps", label: "Mobile Apps" },
      { value: "programming", label: "Programming" },
      { value: "game_development", label: "Game Development" },
      { value: "databases", label: "Databases" },
      { value: "software_testing", label: "Software Testing" },
      { value: "software_engineering", label: "Software Engineering" },
      { value: "development_tools", label: "Development Tools" },
      { value: "ecommerce", label: "Ecommerce" },
      { value: "python", label: "Python" },
      { value: "ai_agents_agentic_ai", label: "AI Agents & Agentic AI" },
      { value: "artificial_intelligence", label: "Artificial Intelligence (AI)" },
      { value: "unreal_engine", label: "Unreal Engine" },
      { value: "data_science", label: "Data Science" },
      { value: "react_js", label: "React JS" },
      { value: "java", label: "Java" },
      { value: "unity", label: "Unity" },
      { value: "large_language_models", label: "Large Language Models (LLM)" },
      { value: "csharp", label: "C# (programming language)" },
      { value: "javascript", label: "JavaScript" },
      { value: "generative_ai", label: "Generative AI (GenAI)" },
      { value: "machine_learning", label: "Machine Learning" },
      { value: "cpp", label: "C++ (programming language)" },
      { value: "game_development_fundamentals", label: "Game Development Fundamentals" },
      { value: "google_flutter", label: "Google Flutter" },
      { value: "sql", label: "SQL" },
      { value: "angular", label: "Angular" },
      { value: "docker", label: "Docker" },
    ],
  },
  {
    value: "business",
    label: "Business",
    children: [
      { value: "entrepreneurship", label: "Entrepreneurship" },
      { value: "communication", label: "Communication" },
      { value: "management", label: "Management" },
      { value: "sales", label: "Sales" },
      { value: "strategy", label: "Strategy" },
      { value: "operations", label: "Operations" },
      { value: "project_management", label: "Project Management" },
      { value: "business_law", label: "Business Law" },
      { value: "data_analytics", label: "Data Analytics" },
      { value: "home_business", label: "Home Business" },
      { value: "human_resources", label: "Human Resources" },
      { value: "industry", label: "Industry" },
      { value: "media", label: "Media" },
      { value: "real_estate", label: "Real Estate" },
      { value: "other", label: "Other" },
      { value: "pmp", label: "PMI Project Management Professional (PMP)" },
      { value: "microsoft_power_bi", label: "Microsoft Power BI" },
      { value: "project_management", label: "Project Management" },
      { value: "sql", label: "SQL" },
      { value: "capm", label: "PMI Certified Associate in Project Management (CAPM)" },
      { value: "pmbok", label: "PMI PMBOK" },
      { value: "data_analysis", label: "Data Analysis" },
      { value: "data_modeling", label: "Data Modeling" },
      { value: "artificial_intelligence", label: "Artificial Intelligence (AI)" },
      { value: "real_estate_investing", label: "Real Estate Investing" },
      { value: "business_analysis", label: "Business Analysis" },
      { value: "generative_ai", label: "Generative AI (GenAI)" },
      { value: "communication_skills", label: "Communication Skills" },
      { value: "business_strategy", label: "Business Strategy" },
      { value: "chatgpt", label: "ChatGPT" },
      { value: "product_management", label: "Product Management" },
      { value: "sales_skills", label: "Sales Skills" },
      { value: "human_resources", label: "Human Resources" },
      { value: "leadership", label: "Leadership" },
      { value: "business_fundamentals", label: "Business Fundamentals" },
      { value: "finance", label: "Finance" }, // keep for backward compatibility if needed
      { value: "python", label: "Python" },
      { value: "microsoft_excel", label: "Microsoft Excel" },
    ],
  },
  {
    value: "finance",
    label: "Finance",
    children: [
      { value: "finance_accounting", label: "Finance & Accounting" },
      { value: "stock_trading", label: "Stock Trading" },
      { value: "investing", label: "Investing" },
      { value: "financial_analysis", label: "Financial Analysis" },
      { value: "accounting", label: "Accounting" },
      { value: "forex_trading", label: "Forex Trading" },
      { value: "day_trading", label: "Day Trading" },
      { value: "technical_analysis", label: "Technical Analysis (finance)" },
      { value: "quickbooks", label: "QuickBooks" },
      { value: "algorithmic_trading", label: "Algorithmic Trading" },
      { value: "financial_modeling", label: "Financial Modeling" },
      { value: "options_trading", label: "Options Trading" },
      { value: "cryptocurrency", label: "Cryptocurrency" },
      { value: "financial_markets", label: "Financial Markets" },
      { value: "bookkeeping", label: "Bookkeeping" },
      { value: "finance_fundamentals", label: "Finance Fundamentals" },
      { value: "personal_finance", label: "Personal Finance" },
      { value: "financial_trading", label: "Financial Trading" },
      { value: "aml", label: "Anti-Money Laundering (AML)" },
      { value: "microsoft_excel", label: "Microsoft Excel" },
      { value: "python", label: "Python" },
    ],
  },
  {
    value: "it_software",
    label: "IT & Software",
    children: [
      { value: "it_certification", label: "IT Certification" },
      { value: "network_security", label: "Network & Security" },
      { value: "hardware", label: "Hardware" },
      { value: "operating_systems", label: "Operating Systems" },
      { value: "other", label: "Other" },
      { value: "aws_solutions_architect_associate", label: "AWS Certified Solutions Architect - Associate" },
      { value: "aws_cloud_practitioner", label: "AWS Certified Cloud Practitioner" },
      { value: "comptia_security_plus", label: "CompTIA Security+" },
      { value: "comptia_a_plus", label: "CompTIA A+" },
      { value: "amazon_aws", label: "Amazon AWS" },
      { value: "ccna", label: "Cisco Certified Network Associate (CCNA)" },
      { value: "ethical_hacking", label: "Ethical Hacking" },
      { value: "comptia_network_plus", label: "CompTIA Network+" },
      { value: "information_security", label: "Information Security" },
      { value: "cybersecurity", label: "Cybersecurity" },
      { value: "kubernetes", label: "Kubernetes" },
      { value: "aws_ai_practitioner", label: "AWS Certified AI Practitioner" },
      { value: "linux", label: "Linux" },
      { value: "az900", label: "AZ-900: Microsoft Azure Fundamentals" },
      { value: "artificial_intelligence", label: "Artificial Intelligence (AI)" },
      { value: "devops", label: "DevOps" },
      { value: "aws_genai_developer", label: "AWS Certified Generative AI Developer - Professional" },
      { value: "az104", label: "AZ-104: Microsoft Azure Administrator Associate" },
      { value: "aws_developer_associate", label: "AWS Certified Developer - Associate" },
      { value: "aigp", label: "Artificial Intelligence Governance Professional (AIGP)" },
    ],
  },
  {
    value: "office_productivity",
    label: "Office Productivity",
    children: [
      { value: "microsoft", label: "Microsoft" },
      { value: "apple", label: "Apple" },
      { value: "google", label: "Google" },
      { value: "sap", label: "SAP" },
      { value: "intuit", label: "Intuit" },
      { value: "salesforce", label: "Salesforce" },
      { value: "oracle", label: "Oracle" },
      { value: "other", label: "Other" },
      { value: "microsoft_excel", label: "Microsoft Excel" },
      { value: "chatgpt", label: "ChatGPT" },
      { value: "microsoft_power_bi", label: "Microsoft Power BI" },
      { value: "sap", label: "SAP" },
      { value: "microsoft_365", label: "Microsoft 365 (Office)" },
      { value: "microsoft_copilot", label: "Microsoft Copilot" },
      { value: "powerpoint", label: "PowerPoint" },
      { value: "excel_vba", label: "Excel VBA" },
      { value: "excel_formulas_functions", label: "Excel Formulas and Functions" },
      { value: "microsoft_sharepoint", label: "Microsoft SharePoint" },
      { value: "pivot_tables", label: "Pivot Tables" },
      { value: "artificial_intelligence", label: "Artificial Intelligence (AI)" },
      { value: "microsoft_power_automate", label: "Microsoft Power Automate" },
      { value: "google_sheets", label: "Google Sheets" },
      { value: "data_analysis", label: "Data Analysis" },
      { value: "google_gemini", label: "Google Gemini (Bard)" },
      { value: "sap_s4hana", label: "SAP S/4HANA" },
      { value: "microsoft_project", label: "Microsoft Project" },
      { value: "microsoft_word", label: "Microsoft Word" },
      { value: "power_pivot", label: "Power Pivot" },
    ],
  },
  {
    value: "personal_development",
    label: "Personal Development",
    children: [
      { value: "personal_transformation", label: "Personal Transformation" },
      { value: "leadership", label: "Leadership" },
      { value: "productivity", label: "Productivity" },
      { value: "personal_finance", label: "Personal Finance" },
      { value: "career_development", label: "Career Development" },
      { value: "parenting_relationships", label: "Parenting & Relationships" },
      { value: "happiness", label: "Happiness" },
      { value: "religion_spirituality", label: "Religion & Spirituality" },
      { value: "personal_brand_building", label: "Personal Brand Building" },
      { value: "creativity", label: "Creativity" },
      { value: "influence", label: "Influence" },
      { value: "self_esteem", label: "Self Esteem" },
      { value: "stress_management", label: "Stress Management" },
      { value: "memory_study_skills", label: "Memory & Study Skills" },
      { value: "motivation", label: "Motivation" },
      { value: "other", label: "Other" },
      { value: "generative_ai", label: "Generative AI (GenAI)" },
      { value: "life_coach_training", label: "Life Coach Training" },
      { value: "chatgpt", label: "ChatGPT" },
      { value: "communication_skills", label: "Communication Skills" },
      { value: "nlp", label: "Neuro-Linguistic Programming (NLP)" },
      { value: "personal_productivity", label: "Personal Productivity" },
      { value: "speed_reading", label: "Speed Reading" },
      { value: "memory", label: "Memory" },
      { value: "creative_writing", label: "Creative Writing" },
      { value: "coaching", label: "Coaching" },
      { value: "public_speaking", label: "Public Speaking" },
      { value: "time_management", label: "Time Management" },
      { value: "confidence", label: "Confidence" },
      { value: "artificial_intelligence", label: "Artificial Intelligence (AI)" },
      { value: "obsidian_app", label: "Obsidian App" },
      { value: "project_management", label: "Project Management" },
      { value: "spirituality", label: "Spirituality" },
    ],
  },
  {
    value: "design",
    label: "Design",
    children: [
      { value: "web_design", label: "Web Design" },
      { value: "graphic_design", label: "Graphic Design" },
      { value: "design_tools", label: "Design Tools" },
      { value: "user_experience", label: "User Experience" },
      { value: "game_design", label: "Game Design" },
      { value: "design_thinking", label: "Design Thinking" },
      { value: "3d_animation", label: "3D & Animation" },
      { value: "fashion", label: "Fashion" },
      { value: "architectural_design", label: "Architectural Design" },
      { value: "interior_design", label: "Interior Design" },
      { value: "other", label: "Other" },
      { value: "blender", label: "Blender" },
      { value: "graphic_design", label: "Graphic Design" },
      { value: "3d_modeling", label: "3D Modeling" },
      { value: "drawing", label: "Drawing" },
      { value: "figma", label: "Figma" },
      { value: "ux_design", label: "User Experience (UX) Design" },
      { value: "autocad", label: "AutoCAD" },
      { value: "revit", label: "Revit" },
      { value: "canva", label: "Canva" },
      { value: "autodesk_fusion", label: "Autodesk Fusion" },
      { value: "adobe_photoshop", label: "Adobe Photoshop" },
      { value: "adobe_illustrator", label: "Adobe Illustrator" },
      { value: "3d_printing", label: "3D Printing" },
      { value: "adobe_after_effects", label: "Adobe After Effects" },
      { value: "solidworks", label: "SOLIDWORKS" },
      { value: "procreate", label: "Procreate Digital Illustration App" },
      { value: "web_design", label: "Web Design" },
      { value: "pixel_art", label: "Pixel Art" },
      { value: "motion_graphics", label: "Motion Graphics" },
      { value: "interior_design", label: "Interior Design" },
    ],
  },
  {
    value: "marketing",
    label: "Marketing",
    children: [
      { value: "digital_marketing", label: "Digital Marketing" },
      { value: "social_media_marketing", label: "Social Media Marketing" },
      { value: "seo", label: "Search Engine Optimization (SEO)" },
      { value: "marketing_strategy", label: "Marketing Strategy" },
      { value: "google_ads", label: "Google Ads (Adwords)" },
      { value: "social_media_management", label: "Social Media Management" },
      { value: "facebook_ads", label: "Facebook Ads" },
      { value: "youtube_marketing", label: "YouTube Marketing" },
      { value: "instagram_marketing", label: "Instagram Marketing" },
      { value: "internet_marketing", label: "Internet Marketing" },
      { value: "wordpress", label: "WordPress" },
      { value: "facebook_marketing", label: "Facebook Marketing" },
      { value: "copywriting", label: "Copywriting" },
      { value: "canva", label: "Canva" },
      { value: "youtube_audience_growth", label: "YouTube Audience Growth" },
      { value: "ai_content_generation", label: "AI Content Generation" },
      { value: "affiliate_marketing", label: "Affiliate Marketing" },
      { value: "google_analytics", label: "Google Analytics" },
      { value: "chatgpt", label: "ChatGPT" },
      { value: "google_ads_certification", label: "Google Ads Certification" },
    ],
  },
  {
    value: "lifestyle",
    label: "Lifestyle",
    children: [
      { value: "arts_crafts", label: "Arts & Crafts" },
      { value: "food_beverage", label: "Foods & Beverages" },
      { value: "beauty_makeup", label: "Beauty & Makeup" },
      { value: "travel", label: "Travel" },
      { value: "gaming", label: "Gaming" },
      { value: "home_improvement", label: "Home Improvement" },
      { value: "pet_care", label: "Pet Care & Training" },
      { value: "other", label: "Other" },
      { value: "drawing", label: "Drawing" },
      { value: "watercolor_painting", label: "Watercolor Painting" },
      { value: "energy_healing", label: "Energy Healing" },
      { value: "chess", label: "Chess" },
      { value: "sketching", label: "Sketching" },
      { value: "acrylic_painting", label: "Acrylic Painting" },
      { value: "astrology", label: "Astrology" },
      { value: "hypnotherapy", label: "Hypnotherapy" },
      { value: "figure_drawing", label: "Figure Drawing" },
      { value: "spiritual_healing", label: "Spiritual Healing" },
      { value: "cooking", label: "Cooking" },
      { value: "painting", label: "Painting" },
    ],
  },
  {
    value: "photography_video",
    label: "Photography",
    children: [
      { value: "digital_photography", label: "Digital Photography" },
      { value: "photography_fundamentals", label: "Photography Fundamentals" },
      { value: "portraits", label: "Portraits" },
      { value: "landscape", label: "Landscape" },
      { value: "black_white", label: "Black & White" },
      { value: "photography_tools", label: "Photography Tools" },
      { value: "mobile_photography", label: "Mobile Photography" },
      { value: "travel_photography", label: "Travel Photography" },
      { value: "commercial_photography", label: "Commercial Photography" },
      { value: "wedding_photography", label: "Wedding Photography" },
      { value: "wildlife_photography", label: "Wildlife Photography" },
      { value: "video_design", label: "Video Design" },
      { value: "other", label: "Other" },
      { value: "video_editing", label: "Video Editing" },
      { value: "ai_content_generation", label: "AI Content Generation" },
      { value: "davinci_resolve", label: "DaVinci Resolve" },
      { value: "adobe_premiere_pro", label: "Adobe Premiere Pro" },
      { value: "capcut", label: "CapCut" },
      { value: "video_production", label: "Video Production" },
      { value: "adobe_lightroom", label: "Adobe Lightroom" },
      { value: "iphone_photography", label: "iPhone Photography" },
      { value: "adobe_after_effects", label: "Adobe After Effects" },
      { value: "color_grading", label: "Color Grading" },
      { value: "digital_camera_functionality", label: "Digital Camera Functionality" },
      { value: "videography", label: "Videography" },
      { value: "image_editing", label: "Image Editing" },
      { value: "generative_ai", label: "Generative AI (GenAI)" },
      { value: "portrait_photography", label: "Portrait Photography" },
      { value: "filmmaking", label: "Filmmaking" },
      { value: "adobe_photoshop", label: "Adobe Photoshop" },
      { value: "digital_photography", label: "Digital Photography" },
      { value: "final_cut_pro", label: "Final Cut Pro" },
    ],
  },
  {
    value: "health_fitness",
    label: "Health & Fitness",
    children: [
      { value: "fitness", label: "Fitness" },
      { value: "general_health", label: "General Health" },
      { value: "sports", label: "Sports" },
      { value: "nutrition", label: "Nutrition" },
      { value: "yoga", label: "Yoga" },
      { value: "mental_health", label: "Mental Health" },
      { value: "dieting", label: "Dieting" },
      { value: "self_defense", label: "Self Defense" },
      { value: "safety_first_aid", label: "Safety & First Aid" },
      { value: "dance", label: "Dance" },
      { value: "meditation", label: "Meditation" },
      { value: "other", label: "Other" },
      { value: "massage", label: "Massage" },
      { value: "pilates", label: "Pilates" },
      { value: "qigong", label: "Qigong" },
      { value: "breathing_techniques", label: "Breathing Techniques" },
      { value: "health", label: "Health" },
      { value: "cbt", label: "Cognitive Behavioral Therapy (CBT)" },
    ],
  },
  {
    value: "music",
    label: "Music",
    children: [
      { value: "instruments", label: "Instruments" },
      { value: "production", label: "Production" },
      { value: "music_fundamentals", label: "Music Fundamentals" },
      { value: "vocals", label: "Vocals" },
      { value: "music_techniques", label: "Music Techniques" },
      { value: "music_software", label: "Music Software" },
      { value: "other", label: "Other" },
      { value: "guitar", label: "Guitar" },
      { value: "piano", label: "Piano" },
      { value: "music_theory", label: "Music Theory" },
      { value: "music_production", label: "Music Production" },
      { value: "singing", label: "Singing" },
      { value: "ableton_live", label: "Ableton Live" },
      { value: "keyboard_instrument", label: "Keyboard Instrument" },
      { value: "fl_studio", label: "FL Studio" },
      { value: "music_composition", label: "Music Composition" },
      { value: "logic_pro", label: "Logic Pro" },
      { value: "music_mixing", label: "Music Mixing" },
      { value: "songwriting", label: "Songwriting" },
      { value: "sound_design", label: "Sound Design" },
      { value: "bass_guitar", label: "Bass Guitar" },
      { value: "fingerstyle_guitar", label: "Fingerstyle Guitar" },
      { value: "piano_chords", label: "Piano Chords" },
      { value: "drums", label: "Drums" },
      { value: "electronic_music", label: "Electronic Music" },
      { value: "audio_engineering", label: "Audio Engineering" },
    ],
  },
  {
    value: "academics",
    label: "Academics",
    children: [
      { value: "social_science", label: "Social Science" },
      { value: "math_science", label: "Math & Science" },
      { value: "humanities", label: "Humanities" },
      { value: "english_language", label: "English Language" },
      { value: "german_language", label: "German Language" },
      { value: "spanish_language", label: "Spanish Language" },
      { value: "french_language", label: "French Language" },
      { value: "math", label: "Math" },
      { value: "english_grammar", label: "English Grammar" },
      { value: "japanese_language", label: "Japanese Language" },
      { value: "ielts", label: "IELTS" },
      { value: "calculus", label: "Calculus" },
      { value: "statistics", label: "Statistics" },
      { value: "electrical_engineering", label: "Electrical Engineering" },
      { value: "english_conversation", label: "English Conversation" },
      { value: "mandarin_chinese_language", label: "Mandarin Chinese Language" },
      { value: "electrical_circuits", label: "Electrical Circuits" },
      { value: "italian_language", label: "Italian Language" },
      { value: "english_vocabulary", label: "English Vocabulary" },
      { value: "electricity", label: "Electricity" },
      { value: "mechanical_engineering", label: "Mechanical Engineering" },
      { value: "electronics", label: "Electronics" },
      { value: "automotive_engineering", label: "Automotive Engineering" },
    ],
  },
  {
    value: "engineering",
    label: "Engineering",
    children: [
      { value: "electrical_engineering", label: "Electrical Engineering" },
      { value: "mechanical_engineering", label: "Mechanical Engineering" },
      { value: "electronics", label: "Electronics" },
      { value: "automotive_engineering", label: "Automotive Engineering" },
      { value: "electrical_circuits", label: "Electrical Circuits" },
      { value: "electricity", label: "Electricity" },
    ],
  },
  {
    value: "writing",
    label: "Writing",
    children: [
      { value: "creative_writing", label: "Creative Writing" },
      { value: "copywriting", label: "Copywriting" },
    ],
  },
  {
    value: "language",
    label: "Language",
    children: [
      { value: "english", label: "English" },
      { value: "spanish", label: "Spanish" },
      { value: "french", label: "French" },
      { value: "german", label: "German" },
      { value: "japanese", label: "Japanese" },
      { value: "portuguese", label: "Portuguese" },
      { value: "chinese", label: "Chinese" },
      { value: "russian", label: "Russian" },
      { value: "latin", label: "Latin" },
      { value: "arabic", label: "Arabic" },
      { value: "hebrew", label: "Hebrew" },
      { value: "italian", label: "Italian" },
      { value: "other", label: "Other" },
    ],
  },
];
