export const COURSE_CATEGORIES = [
  {
    value: "development",
    label: "Development",
    children: [
      { value: "web_development", label: "Web Development" },
      { value: "mobile_development", label: "Mobile Development" },
      { value: "game_development", label: "Game Development" },
      { value: "programming_languages", label: "Programming Languages" },
      { value: "backend_development", label: "Backend Development" },
      { value: "frontend_development", label: "Frontend Development" },
      { value: "fullstack_development", label: "Full Stack Development" },
      { value: "software_engineering", label: "Software Engineering" },
      { value: "data_programming", label: "Databases & Data Programming" },
    ],
  },
  {
    value: "business",
    label: "Business",
    children: [
      { value: "entrepreneurship", label: "Entrepreneurship" },
      { value: "management", label: "Management" },
      { value: "finance_accounting", label: "Finance & Accounting" },
      { value: "human_resources", label: "Human Resources" },
      { value: "sales", label: "Sales" },
      { value: "business_strategy", label: "Business Strategy" },
      { value: "operations", label: "Operations" },
      { value: "project_management", label: "Project Management" },
      { value: "business_law", label: "Business Law" },
    ],
  },
  {
    value: "marketing",
    label: "Marketing",
    children: [
      { value: "digital_marketing", label: "Digital Marketing" },
      { value: "seo", label: "Search Engine Optimization (SEO)" },
      { value: "social_media_marketing", label: "Social Media Marketing" },
      { value: "content_marketing", label: "Content Marketing" },
      { value: "branding", label: "Branding" },
      { value: "marketing_fundamentals", label: "Marketing Fundamentals" },
      { value: "analytics_growth", label: "Analytics & Growth" },
      { value: "advertising", label: "Advertising" },
      { value: "public_relations", label: "Public Relations" },
      { value: "video_marketing", label: "Video & Mobile Marketing" },
    ],
  },
  {
    value: "it_software",
    label: "IT & Software",
    children: [
      { value: "it_certifications", label: "IT Certifications" },
      { value: "network_security", label: "Network & Security" },
      { value: "cyber_security", label: "Cyber Security" },
      { value: "cloud_computing", label: "Cloud Computing" },
      { value: "devops", label: "DevOps" },
      { value: "operating_systems", label: "Operating Systems" },
      { value: "hardware", label: "Hardware" },
      { value: "software_testing", label: "Software Testing" },
    ],
  },
  {
    value: "design",
    label: "Design",
    children: [
      { value: "graphic_design", label: "Graphic Design" },
      { value: "ui_ux_design", label: "UI/UX Design" },
      { value: "web_design", label: "Web Design" },
      { value: "interior_design", label: "Interior Design" },
      { value: "game_design", label: "Game Design" },
      { value: "3d_animation", label: "3D & Animation" },
      { value: "motion_graphics", label: "Motion Graphics" },
      { value: "fashion_design", label: "Fashion Design" },
      { value: "architectural_design", label: "Architectural Design" },
    ],
  },
  {
    value: "data_science_ai",
    label: "Data Science & AI",
    children: [
      { value: "data_science", label: "Data Science" },
      { value: "machine_learning", label: "Machine Learning" },
      { value: "artificial_intelligence", label: "Artificial Intelligence" },
      { value: "data_analysis", label: "Data Analysis" },
      { value: "big_data", label: "Big Data" },
      { value: "statistics", label: "Statistics" },
      { value: "deep_learning", label: "Deep Learning" },
    ],
  },
  {
    value: "personal_development",
    label: "Personal Development",
    children: [
      { value: "productivity", label: "Productivity" },
      { value: "leadership", label: "Leadership" },
      { value: "communication_skills", label: "Communication Skills" },
      { value: "personal_transformation", label: "Personal Transformation" },
      { value: "happiness", label: "Happiness" },
      { value: "creativity", label: "Creativity" },
      { value: "influence", label: "Influence" },
      { value: "memory_techniques", label: "Memory & Study Skills" },
      { value: "motivation", label: "Motivation" },
    ],
  },
  {
    value: "health_fitness",
    label: "Health & Fitness",
    children: [
      { value: "fitness", label: "Fitness" },
      { value: "general_health", label: "General Health" },
      { value: "yoga", label: "Yoga" },
      { value: "nutrition", label: "Nutrition" },
      { value: "mental_health", label: "Mental Health" },
      { value: "dieting", label: "Dieting" },
      { value: "sports", label: "Sports" },
      { value: "meditation", label: "Meditation" },
      { value: "self_defense", label: "Self Defense" },
    ],
  },
  {
    value: "music",
    label: "Music",
    children: [
      { value: "instruments", label: "Instruments" },
      { value: "music_production", label: "Music Production" },
      { value: "music_fundamentals", label: "Music Fundamentals" },
      { value: "vocal", label: "Vocal" },
      { value: "music_techniques", label: "Music Techniques" },
      { value: "music_software", label: "Music Software" },
    ],
  },
  {
    value: "teaching_academics",
    label: "Teaching & Academics",
    children: [
      { value: "language_learning", label: "Language Learning" },
      { value: "engineering", label: "Engineering" },
      { value: "humanities", label: "Humanities" },
      { value: "math", label: "Math" },
      { value: "science", label: "Science" },
      { value: "social_science", label: "Social Science" },
      { value: "teacher_training", label: "Teacher Training" },
      { value: "test_prep", label: "Test Prep" },
    ],
  },
  {
    value: "lifestyle",
    label: "Lifestyle",
    children: [
      { value: "arts_crafts", label: "Arts & Crafts" },
      { value: "beauty_makeup", label: "Beauty & Makeup" },
      { value: "food_beverage", label: "Food & Beverage" },
      { value: "gaming", label: "Gaming" },
      { value: "home_improvement", label: "Home Improvement" },
      { value: "pet_care", label: "Pet Care & Training" },
      { value: "travel", label: "Travel" },
    ],
  },
  {
    value: "photography_video",
    label: "Photography & Video",
    children: [
      { value: "photography", label: "Photography" },
      { value: "video_design", label: "Video Design" },
      { value: "digital_photography", label: "Digital Photography" },
      { value: "portrait_photography", label: "Portrait Photography" },
      { value: "commercial_photography", label: "Commercial Photography" },
      { value: "photography_tools", label: "Photography Tools" },
    ],
  },
  {
    value: "office_productivity",
    label: "Office Productivity",
    children: [
      { value: "microsoft", label: "Microsoft" },
      { value: "apple", label: "Apple" },
      { value: "google", label: "Google" },
      { value: "sap", label: "SAP" },
      { value: "oracle", label: "Oracle" },
    ],
  },
];